# Generated by Django 4.2.3 on 2023-07-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("priceM", models.DecimalField(decimal_places=2, max_digits=6)),
                ("priceL", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pImage", models.URLField()),
                ("veg_nonveg", models.URLField()),
            ],
        ),
    ]
