# Generated by Django 4.2.3 on 2023-08-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodApp", "0004_alter_item_price_alter_order_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Starter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("sPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("sImage", models.URLField()),
                ("veg_nonveg", models.URLField()),
            ],
        ),
    ]
