# Generated by Django 4.2.3 on 2023-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodApp", "0007_rename_simage_bread_bimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("priceM", models.DecimalField(decimal_places=2, max_digits=6)),
                ("priceL", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pImage", models.URLField()),
                ("veg_nonveg", models.URLField()),
            ],
        ),
    ]
