# Generated by Django 4.2.3 on 2023-08-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodApp", "0009_rice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dessert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("dPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pImage", models.URLField()),
            ],
        ),
    ]
