# Generated by Django 4.2.3 on 2023-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodApp", "0010_dessert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("bPrice", models.DecimalField(decimal_places=2, max_digits=6)),
                ("bImage", models.URLField()),
            ],
        ),
    ]
